services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sub-agent
    env_file:
      - .env
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8
    command: python -u main.py